#!/bin/bash

# Run the system-wide python which is installed as a "framework" install
#   instead of the "non-framework" install in this venv.
# We need a framework install to get matplotlib to work
# Install this script in venv/bin, and (typically) name it: frameworkpython
# Then you can run "frameworkpython x.py y z" instead of  "python x.py y z"
#
# See:
# http://stackoverflow.com/questions/21784641/installation-issue-with-matplotlib-python
# http://matplotlib.org/faq/usage_faq.html#what-is-a-backend
# http://matplotlib.org/faq/virtualenv_faq.html

# what real Python executable to use
PYVER=2.7
PATHTOPYTHON=/usr/bin/
PYTHON=${PATHTOPYTHON}python${PYVER}

# find the root of the virtualenv, it should be the parent of the dir this script is in
ENV=`$PYTHON -c "import os; print(os.path.abspath(os.path.join(os.path.dirname(\"$0\"), '..')))"`

# now run Python with the virtualenv set as Python's HOME
export PYTHONHOME=$ENV
exec $PYTHON "$@"
