#!/bin/bash

# Run the system-wide python with is installed as a "framework" instead
#  of the "non-framework" install in this venv.
# We need a framework install to get matplotlib to work
# (keep fingers crossed)
# Install in venv/bin

# what real Python executable to use
PYVER=2.7
PATHTOPYTHON=/usr/bin/
PYTHON=${PATHTOPYTHON}python${PYVER}

# find the root of the virtualenv, it should be the parent of the dir this script is in
ENV=`$PYTHON -c "import os; print(os.path.abspath(os.path.join(os.path.dirname(\"$0\"), '..')))"`

# now run Python with the virtualenv set as Python's HOME
export PYTHONHOME=$ENV
exec $PYTHON "$@"
